import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';

import Footer from '@/components/Footer';
import NavBar from '@/components/Navbar';
import Providers from './providers';
import SyncSupabaseSession from '@/utils/syncSupabaseSession';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'StudyPalz',
  description: 'Generated by ics-software-engineering.github.io',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const classString = `${inter.className} wrapper`;

  return (
    <html lang="en">
      <body className={classString}>
        <Providers>
          {/* Sync NextAuth session into Supabase */}
          <SyncSupabaseSession />

          <NavBar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}